### ISSUE TITLE
จองห้องเลือก หน่วยงานแล้ว แต่ระบบไม่บันทึก

### ISSUE THREAD

**Issue by nine-m** [goragod/eoffice#2]
จองห้องเลือก หน่วยงานแล้ว แต่ระบบไม่บันทึก จะบันทึกเป็นหน่วยงานลำดับที่ 1 ใน list เท่านั้น

**Comment by goragodwiriya** [comment]
ผมทดสอบบนเว็บไซต์ตัวอย่างก็ปกตินะครับ ไม่ทราบว่าทดสอบที่ไหน มี error หรือไม่
เบื่องต้น ลองดำเนินการตามนี้ดูก่อนครับ https://kotchasan.com/forum.html?wbid=3809 แล้วแจ้งผลมาอีกที

**Comment by goragodwiriya** [comment]
อัปเดทตอนนี้เลยครับ
